In [ ]:
import torch

****

In [ ]:
#Empty function
a= torch.empty(3,3)
a
# Empty function just create meomory allocation

tensor([[2.1157e+23, 3.4304e-06, 1.6968e-07],
        [1.4580e-19, 7.1429e+31, 1.5766e-19],
        [1.0256e-08, 2.6252e-06, 3.0956e+12]])

In [3]:
#Type of Function
type(a)

torch.Tensor

In [4]:
#Zeros Function
b=torch.zeros(2,3)
b
#Creation of tensor according to your need of zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
#Ones Function
c=torch.ones(3,3)
c

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

**Random Func**

In [6]:
a=torch.rand(2,3)
a
#Every time we run, we get different number .

tensor([[0.7753, 0.1250, 0.8221],
        [0.1939, 0.2004, 0.8177]])

In [7]:
#use of Seed.
# To get same random number every time, then we use manual_seed.
a=torch.manual_seed(30)
a=torch.rand(2,3)
a

tensor([[0.9007, 0.7464, 0.4716],
        [0.8738, 0.7403, 0.7840]])

In [9]:
a=torch.manual_seed(30)
a=torch.rand(2,3)
a

tensor([[0.9007, 0.7464, 0.4716],
        [0.8738, 0.7403, 0.7840]])

In [8]:
a=torch.rand(2,3)
a

tensor([[0.8946, 0.6238, 0.4276],
        [0.8421, 0.7454, 0.6181]])

**Custom Tensors**

In [11]:
#Put your value to your own.
a=torch.tensor([[[1,2,3]],[[2,3,5]]])
a
# 3D Tensor in Pytorch

tensor([[[1, 2, 3]],

        [[2, 3, 5]]])

In [12]:
#1D Tensor
b=torch.tensor([1,2,4,5])
b

tensor([1, 2, 4, 5])

In [14]:
#2D Tensor
c=torch.tensor([[1,2,4,5],[34,522,45,6666666]])
c

tensor([[      1,       2,       4,       5],
        [     34,     522,      45, 6666666]])

In [15]:
type(c)

torch.Tensor

In [16]:
#Arange Func in Pytorch
a=torch.arange(0,9,3)
a

tensor([0, 3, 6])

In [17]:
#Linspace
#linspace divided the total value into equal parts
a=torch.linspace(0,11,4)

In [18]:
a

tensor([ 0.0000,  3.6667,  7.3333, 11.0000])

In [19]:
#Eye Function
#Eye function means identity matrix.
a=torch.eye(3)

In [20]:
a

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [21]:
a=torch.eye(11)
a

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
#full func
#Here we describe we need 3 by 3 tensor and every item should be 5.
a=torch.full((3,3),5)
a

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])