In [1]:
import torch

Element Wise Operations

In [3]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)

print(b)

tensor([[0.7637, 0.8866, 0.8099],
        [0.8957, 0.4169, 0.0175]])
tensor([[0.8851, 0.2933, 0.3221],
        [0.5704, 0.3997, 0.8303]])


In [4]:
a+b

tensor([[1.6488, 1.1798, 1.1320],
        [1.4661, 0.8166, 0.8478]])

In [5]:
a-b

tensor([[-0.1214,  0.5933,  0.4879],
        [ 0.3253,  0.0172, -0.8129]])

In [6]:
a*b

tensor([[0.6759, 0.2600, 0.2609],
        [0.5109, 0.1666, 0.0145]])

In [7]:
a/b

tensor([[0.8628, 3.0233, 2.5147],
        [1.5704, 1.0429, 0.0210]])

In [8]:
a%b

tensor([[0.7637, 0.0068, 0.1658],
        [0.3253, 0.0172, 0.0175]])

In [11]:
c=torch.tensor([1,-2,3-4])
c

tensor([ 1, -2, -1])

In [12]:
#abs
torch.abs(c)

tensor([1, 2, 1])

In [13]:
torch.neg(c)

tensor([-1,  2,  1])

In [14]:
d=torch.tensor([1.9,2.3,3.3,7.4])
d

tensor([1.9000, 2.3000, 3.3000, 7.4000])

In [15]:
torch.round(d)

tensor([2., 2., 3., 7.])

In [16]:
torch.ceil(d)

tensor([2., 3., 4., 8.])

In [18]:
torch.floor(d)

tensor([1., 2., 3., 7.])

In [21]:
#Clamp func
#giving the range to the func.
torch.clamp(d,min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])


Reduction Operation

In [24]:
e=torch.randint(size =(2,3),low=2,high=10)
print(e)

tensor([[3, 9, 3],
        [5, 3, 6]])


In [28]:
#Sum
torch.sum(e)
#Sum along columns
torch.sum(e, dim=0)
#Sum along rows
torch.sum(e, dim=1)

tensor([15, 14])

Inplace Operations


In [31]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.3374, 0.1480, 0.6205],
        [0.5555, 0.6709, 0.0964]])
tensor([[0.4796, 0.1742, 0.3505],
        [0.1031, 0.6747, 0.2645]])


In [37]:
a.add_(b)

tensor([[0.8170, 0.3222, 0.9709],
        [0.6587, 1.3456, 0.3609]])

In [38]:
a

tensor([[0.8170, 0.3222, 0.9709],
        [0.6587, 1.3456, 0.3609]])

In [39]:
b

tensor([[0.4796, 0.1742, 0.3505],
        [0.1031, 0.6747, 0.2645]])

In [41]:
a.relu_()
#underscore is make a permanent change in variable.

tensor([[0.8170, 0.3222, 0.9709],
        [0.6587, 1.3456, 0.3609]])

Copying Tensor

In [45]:
a=torch.rand(2,3)
a

tensor([[0.9835, 0.8187, 0.9656],
        [0.4044, 0.9945, 0.1959]])

In [46]:
b=a

In [47]:
b

tensor([[0.9835, 0.8187, 0.9656],
        [0.4044, 0.9945, 0.1959]])

In [48]:
b=a.clone()

In [49]:
b

tensor([[0.9835, 0.8187, 0.9656],
        [0.4044, 0.9945, 0.1959]])

Tensor Operation on GPU

In [3]:
import torch

In [5]:
torch.cuda.is_available()


True

In [6]:
device=torch.device('cuda')

In [7]:
torch.rand((2,3),device=device)

tensor([[0.3221, 0.6581, 0.0168],
        [0.8459, 0.9559, 0.6488]], device='cuda:0')

In [9]:
a=torch.rand(2,3)

In [10]:
a

tensor([[0.5879, 0.3954, 0.5867],
        [0.1262, 0.3585, 0.5446]])

In [13]:
b=a.to(device)

In [14]:
b

tensor([[0.5879, 0.3954, 0.5867],
        [0.1262, 0.3585, 0.5446]], device='cuda:0')

In [15]:
b+5

tensor([[5.5879, 5.3954, 5.5867],
        [5.1262, 5.3585, 5.5446]], device='cuda:0')

Reshaping Tensor


In [16]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [19]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
#flaten
b=torch.rand(2,3,4)
b
b.flatten()

tensor([0.0525, 0.0376, 0.1071, 0.8583, 0.3039, 0.3509, 0.7431, 0.5948, 0.5050,
        0.6337, 0.2238, 0.2831, 0.4349, 0.5317, 0.8600, 0.2777, 0.1423, 0.7240,
        0.0032, 0.2724, 0.1029, 0.8090, 0.9762, 0.5769])

In [21]:
#Permute
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [22]:
#Unsqueez
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [23]:
c=torch.rand(226,226,3)
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [25]:
#Squeez
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

Numpy to Pytorch vs Pytorch to Numpy

In [ ]:
import numpy as np
