In [1]:
import torch

In [4]:
(torch.__version__)

'2.6.0+cu124'

**Shapes**

In [2]:
a=torch.tensor([[1,2,3],[3,4,5]])
a.shape

torch.Size([2, 3])

In [6]:
#Empty Func
#If you want to create the same type tensor.
b=torch.empty_like(a)

In [8]:
b

tensor([[    135107203779936,     135107203779936, 2459014313495306786],
        [4189037551708894323, 4189048190192788000,                  97]])

In [9]:
torch.zeros_like(a)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [10]:
torch.ones_like(a)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [12]:
#Find Data types of the func
a.dtype

torch.int64

In [16]:
#Assign Data Types
a=torch.tensor([3,4,5,6],dtype=torch.float64)
a

tensor([3., 4., 5., 6.], dtype=torch.float64)

In [17]:
b=torch.tensor([2.0,3.3], dtype=torch.int)
b

tensor([2, 3], dtype=torch.int32)

In [18]:
a.to(torch.float32)
a

tensor([3., 4., 5., 6.], dtype=torch.float64)

Mathamatical Operations


In [19]:
x=torch.rand(2,2)
x

tensor([[0.3542, 0.2557],
        [0.4772, 0.0530]])

In [20]:
#Addition Func
x

tensor([[0.3542, 0.2557],
        [0.4772, 0.0530]])

In [21]:
x+2

tensor([[2.3542, 2.2557],
        [2.4772, 2.0530]])

In [22]:
#Multiplication Func
x*2

tensor([[0.7083, 0.5115],
        [0.9545, 0.1060]])

In [23]:
#Divide
x/2

tensor([[0.1771, 0.1279],
        [0.2386, 0.0265]])

In [24]:
#Subtraction
x-2

tensor([[-1.6458, -1.7443],
        [-1.5228, -1.9470]])

In [25]:
#int division func
(x*100)//3

tensor([[11.,  8.],
        [15.,  1.]])

In [26]:
#Mod
((x*100)//3)%3

tensor([[2., 2.],
        [0., 1.]])